In [1]:
import numpy as np

In [2]:
# create an array

a =np.array([2,4,5,6,8])
a

array([2, 4, 5, 6, 8])

In [3]:
# checking the dimension

a.ndim

1

In [4]:
## create a two dimensional array

s=np.array([[1,2,3],[2,3,4]])
s

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
s.ndim

2

In [7]:
## create a three dimensional array

c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])



In [8]:
c.ndim

3

## Functions

In [9]:
arr = np.array([22,24,28,18])

In [10]:
type(arr)

numpy.ndarray

In [12]:
arr.argmax() # index of max value in the Array

2

In [13]:
arr.argmin() # index of min value in the Array

3

In [14]:
arr[1]

24

In [15]:
arr[1:]

array([24, 28, 18])

In [16]:
arr[0:-1]

array([22, 24, 28])

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr.size

4

In [20]:
# create a numpy array with size 5 and datatype of float


a= np.array([20.5,216,236,256,277])


In [21]:
a.dtype

dtype('float64')

In [ ]:
## Create a two dim array
## four arrays in the external array
## it should have two elements in each

In [22]:
arr1 = np.array([[1,2],[4,3],[7,8],[1,9]])
arr1

array([[1, 2],
       [4, 3],
       [7, 8],
       [1, 9]])

In [23]:
arr1.ndim

2

## Resize and reshape 

In [25]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
b.shape

(4, 3)

In [30]:
b.max()

11

In [31]:
b.min()

0

In [32]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [33]:
np.log(b)

<ipython-input-33-3f8f764f67ee>:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [34]:
np.exp(b)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [35]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Transpose

In [37]:
b1=b.T
b1

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

## floor and ceil

In [38]:
arr2 = np.array([10.8,2.1,4.25,7.81])
arr2

array([10.8 ,  2.1 ,  4.25,  7.81])

In [39]:
np.floor(arr2)

array([10.,  2.,  4.,  7.])

In [40]:
np.ceil(arr2)

array([11.,  3.,  5.,  8.])

In [41]:
np.round(arr2)

array([11.,  2.,  4.,  8.])

## stacking

In [42]:
arr23 = np.arange(10).reshape(2,5)
arr24 = np.arange(20).reshape(4,5)


In [43]:
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr24

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
np.vstack((arr23,arr24))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
np.hstack((arr23,arr24))   # its not possible as the number of rows are not equal

ValueError: ignored

In [48]:
arr12=np.arange(12).reshape(3,4)
arr13=np.arange(9).reshape(3,3)

In [49]:
np.hstack((arr12,arr13))

array([[ 0,  1,  2,  3,  0,  1,  2],
       [ 4,  5,  6,  7,  3,  4,  5],
       [ 8,  9, 10, 11,  6,  7,  8]])

## Numpy Split

In [50]:
arr28 = np.arange(100).reshape(10,10)

In [51]:
arr28

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
np.vsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [53]:
np.hsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]